"yolo": {
  "version": 'yolov5s', # or yolov5s, yolov5m, yolov5l, yolov5x, custom
  "folder": "ultralytics/yolov5"
}

"stall_colors": {
      'free' : [0,255,0],
      'busy' : [255,0,0]
}

"classes_to_detect": {
        2: 'car',
        5: 'bus',
        7: 'truck',
}

