"yolo": {
  "checkpoint": "",
  "tsize": 1280,
  "device": 'gpu',
  "confidence": 0.2,
  "nms": 0.45
}

"stall_colors": {
      'free' : [0,255,0],
      'busy' : [255,0,0]
}

"classes_to_detect": {
        2: 'car',
        5: 'bus',
        7: 'truck',
}

